---
- hosts: testservers
  tasks:
    - name: install yum-utils 
      yum: name=yum-utils state=present

    - name: install device-mapper-persistent-data
      yum: name=device-mapper-persistent-data state=present

    - name: install lvm2 
      yum: name=lvm2 state=present

    - name: install wget 
      yum: name=wget state=present

    - name: install bridge-utils 
      yum: name=bridge-utils state=present

    - name: download docker-ce.repo
      get_url:
        url: http://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
    # - script: /ansible/shell/selinuxinstall.sh 
    - name: install docker-ce 
      yum: name=docker-ce state=present update_cache=yes

    - name: show docker version
      command: docker --version 

    - name: copy docker daemon.json 
      copy:
        src: /etc/docker/daemon.json 
        dest: /etc/docker/daemon.json 
    
    - service:
        name: docker 
        state: started
 
