---
- hosts: testservers

  vars:
    #redisfilepath: /software/redis-4.0.11.tar.gz
    mavenfilepath: /software/maven/apache-maven-3.6.2-bin.zip
    bashrcconfig: /config/bashrc

  tasks:
    - name: "demo shell"
      shell: echo start `date`


    - name: install unzip 
      yum: name=unzip state=present
      tags: unzip
 
    #- name: "create direction"
    #  file:
    #    path: /software
    #    state: directory
    #    mode: 0755

    #- name: copy redis to appservers 
    #  copy:
    #    src: '{{redisfilepath}}'
    #    dest: /software
    #    owner: root
    #    group: root
    #    mode: 0644
    #
   
    - name: copy bashrc config 
      copy:
        src: '{{bashrcconfig}}'
        dest: ~/.bashrc 
        owner: root
        group: root
        mode: 0644
      tags: bashrc
       #
   
   


    - name: echo java_version
      command: java -version
      tags: javaversion

    - name: Unarchive a file that needs to be downloaded (added in 2.0)
      unarchive:
        src: '{{mavenfilepath}}'
        dest: /usr/local
        remote_src: no # ansible主机存在
       # remote_src: yes
